### PR TITLE
add TypeScript version

### PR DESCRIPTION
**Pull request by ilandikov**
Hi =)

I've participated to https://github.com/LearnWithLlew/OpenLearningHour?tab=readme-ov-file on 10th of April 2024 with you and couldn't do the exercise because TypeScript was not available. So I took the JS version and converted it into TypeScript. Hope it will be useful for you.

I used the technique you proposed in my project instead of using mocks and it is so much simpler and easier! Thanks a lot =)

### CODE REVIEW

**Comment by codecop** [comment]
Thank you. This looks good. Maybe you could remove the lock file (and ignore it) as for exercises we do not store it as all people have different setup etc.

**Comment by ilandikov** [comment]
Done

**Comment by codecop** [comment]
Thank you. @emilybache this could be merged

**Comment by emilybache** [comment]
Thankyou!

**Pull request merged**
